//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoBook.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Globalization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Globalization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DemoBook.Resources.Globalization", typeof(Globalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        internal static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        internal static string WrongOption {
            get {
                return ResourceManager.GetString("WrongOption", resourceCulture);
            }
        }
        
        internal static string ServiceTitle {
            get {
                return ResourceManager.GetString("ServiceTitle", resourceCulture);
            }
        }
        
        internal static string BookTitleMessage {
            get {
                return ResourceManager.GetString("BookTitleMessage", resourceCulture);
            }
        }
        
        internal static string ReturnCreate {
            get {
                return ResourceManager.GetString("ReturnCreate", resourceCulture);
            }
        }
        
        internal static string AuthorMessage {
            get {
                return ResourceManager.GetString("AuthorMessage", resourceCulture);
            }
        }
        
        internal static string CategoryMessage {
            get {
                return ResourceManager.GetString("CategoryMessage", resourceCulture);
            }
        }
        
        internal static string newTitle {
            get {
                return ResourceManager.GetString("newTitle", resourceCulture);
            }
        }
        
        internal static string newAuthor {
            get {
                return ResourceManager.GetString("newAuthor", resourceCulture);
            }
        }
        
        internal static string newCategory {
            get {
                return ResourceManager.GetString("newCategory", resourceCulture);
            }
        }
        
        internal static string UpdateTitleMessage {
            get {
                return ResourceManager.GetString("UpdateTitleMessage", resourceCulture);
            }
        }
        
        internal static string UpdateMessage {
            get {
                return ResourceManager.GetString("UpdateMessage", resourceCulture);
            }
        }
        
        internal static string notFound {
            get {
                return ResourceManager.GetString("notFound", resourceCulture);
            }
        }
        
        internal static string bookAvailable {
            get {
                return ResourceManager.GetString("bookAvailable", resourceCulture);
            }
        }
        
        internal static string emptyBooks {
            get {
                return ResourceManager.GetString("emptyBooks", resourceCulture);
            }
        }
        
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        internal static string ISBN {
            get {
                return ResourceManager.GetString("ISBN", resourceCulture);
            }
        }
        
        internal static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        internal static string isAvailable {
            get {
                return ResourceManager.GetString("isAvailable", resourceCulture);
            }
        }
        
        internal static string Positive {
            get {
                return ResourceManager.GetString("Positive", resourceCulture);
            }
        }
        
        internal static string Negative {
            get {
                return ResourceManager.GetString("Negative", resourceCulture);
            }
        }
        
        internal static string ReadAll {
            get {
                return ResourceManager.GetString("ReadAll", resourceCulture);
            }
        }
        
        internal static string SearchBook {
            get {
                return ResourceManager.GetString("SearchBook", resourceCulture);
            }
        }
        
        internal static string SearchBookMessage {
            get {
                return ResourceManager.GetString("SearchBookMessage", resourceCulture);
            }
        }
        
        internal static string SearchBookResponse {
            get {
                return ResourceManager.GetString("SearchBookResponse", resourceCulture);
            }
        }
        
        internal static string ISBNError {
            get {
                return ResourceManager.GetString("ISBNError", resourceCulture);
            }
        }
        
        internal static string DeleteBook {
            get {
                return ResourceManager.GetString("DeleteBook", resourceCulture);
            }
        }
        
        internal static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
    }
}
